name: deploy
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  release-containers:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_tag
      shell: bash
      run: echo ::set-output name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
    - uses: ./.github/actions/build-push-lvp-image
      with:
        image-name: index.docker.io/replicated/local-volume-provider:${{ steps.get_tag.outputs.GIT_TAG }}
        git-tag: ${{ steps.get_tag.outputs.GIT_TAG }}
        registry-username: ${{ secrets.DOCKERHUB_USER }}
        registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
