name: unit-tests
on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    - name: Run unit tests
      run: |
        make test